### ISSUE TITLE
Effective Testing with Java Q&A

### ISSUE THREAD

**Issue by sdaschner** [sdaschner/live-qa-sessions#1]
Live on Wed, 8th April, 2020 at 6 pm CEST / 12 pm EDT / 9 am PDT, for 45 mins.

Watch [here](https://www.youtube.com/watch?v=u_JE2_4Z8Sg)

For more information, which material to watch upfront, see this [blog post](https://blog.sebastian-daschner.com/entries/testing-question-answer-session-april).

**Comment by AppLoidx** [comment]
Hi there!

I am not a tester, but as a matter of duty I should write them :)

How to write tests so that we can change the application logic without any problems. 
Because it happens that we cover the code with tests, but then it turns out that we have to change something. And we have to delete all written tests.

I didn't write tests in Java EE stack, but I think there are no special differences with spring

thank u :)

**Comment by dkrtic** [comment]
Hi Sebastian,

how would you change the `CoffeeOrderSystem` class from your system test to test the JAX-RS endpoint secured by MP JWT Authentication ?
Would you just start Keycloak or something similar with Docker and fetch the authorization token from it ? Or would you use [JWTenizr](https://jwtenizr.sh/) or something else ?

Thanks!

**Comment by sdaschner** [comment]
Via [Twitter](https://twitter.com/ProJavaOrlovsky/status/1247870987128930305): What is your take on Java Enterprise or Spring  or some legacy JBoss or even Microprofile or maybe Reactive Java.

**Comment by sdaschner** [comment]
Via email: What about this separation of the projects, why are you using this extra system test project (incl. source code)?

**Comment by sdaschner** [comment]
Via email:

Your "use case test" approach with plain JUnit runner makes sense, but wouldn't it further improve the code quality to add Spock/Groovy testing?

Also is there an approach to use Testcontainers with your approach of a local system tests that gives short feedback/no-startup time?

**Comment by sdaschner** [comment]
Thanks for joining!

You can find some more resources here:

- [Video course](https://blog.sebastian-daschner.com/entries/efficient-testing-video-course)
- [Article series](https://blog.sebastian-daschner.com/entries/thoughts-on-efficient-testing)
- [Quarkus using JWT](https://quarkus.io/guides/security-jwt)
- [Securing microservices with JSON Web Tokens](https://openliberty.io/guides/microprofile-jwt.html#trying-more-jax-rs-methods-to-validate-tokens)
- [Local development with Testcontainers](https://bsideup.github.io/posts/local_development_with_testcontainers/)
