### ISSUE TITLE
Effective keyboard usage for developers Q&A

### ISSUE THREAD

**Issue by sdaschner** [sdaschner/live-qa-sessions#2]
Live on Wed, 22nd April, 2020 at 6 pm CEST / 12 pm EDT / 9 am PDT, for 45 mins.

Watch [here](https://www.youtube.com/watch?v=_zYeGnAVzhY)

For more information see this [blog post](https://blog.sebastian-daschner.com/entries/keyboard-usage-question-answer-session-april).

**Comment by sdaschner** [comment]
Via Twitter DM: What you're take on browsing a website, should I make use of all the keyboards as well? I use the mouse for that a lot and I don't know if I'm much faster. I'm using Chrome.

**Comment by sdaschner** [comment]
Via Twitter DM: I'm eager to learn more about the Linux CLI, which commands and "piping features" do you think we have to know?

**Comment by sdaschner** [comment]
Via email: I like your ideas on making the OS usage more productive. Unfortunately I have to use Windows at work, are there any tips how to make that better?

**Comment by sdaschner** [comment]
Via Twitter: Can you share your IntelliJ live templates?

**Comment by akindo** [comment]
What are your thoughts of VS Code vs. IntelliJ? Depends on personal preference, the task, and/or language?

**Comment by sdaschner** [comment]
Thanks a lot for joining!
