### ISSUE TITLE
Ask me anything Q&A

### ISSUE THREAD

**Issue by sdaschner** [sdaschner/live-qa-sessions#4]
Live on Mon, 27th July, 2020 at 6 pm CEST / 12 pm EDT / 9 am PDT, for 45 mins.

Watch [here](https://www.youtube.com/watch?v=vwFSmaxg-do)

For more information, see this [blog post](https://blog.sebastian-daschner.com/entries/ask-me-anything-session-july).

**Comment by sdaschner** [comment]
Via email: How do you become a Java Champion?

**Comment by sdaschner** [comment]
Via DM: How does your day as a developer advocate for IBM look like? And since you are a coffee lover (I can see from your code examples), what is your favorite coffee drink? :)

**Comment by nheidloff** [comment]
Hi Sebastian, I asked a question on StackOverflow and haven't received a good answer yet: https://stackoverflow.com/questions/62692829/how-to-use-idtoken-in-quarkus-apps-when-application-type-service

Why does @IdToken not work for application type "service" (only for "web-app")? Is this a MicroProfile limitation or Quarkus issue? Or does it work as designed? My assumption was that JWT tokens always contain an id and access token.

**Comment by nheidloff** [comment]
Hi Sebastian, another question: When does app modernization make sense and when not? In other words when should applications use cloud-native technologies and when would it be better to continue using monoliths (either on prem on in VMs in the cloud)?

**Comment by sdaschner** [comment]
Thanks for attending!
